// <auto-generated />
using System;
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlogApi.Migrations
{
    [DbContext(typeof(BlogDbContext))]
    partial class BlogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("BlogApi.Models.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("author");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("text")
                        .HasColumnName("created_at");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tags");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("text")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Logan Tolbert",
                            Content = "This article covers the basics of C# programming language.",
                            CreatedAt = new DateTime(2025, 5, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Tags = "C#,Programming,Basics",
                            Title = "Introduction to C#",
                            UpdatedAt = new DateTime(2025, 5, 9, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            Author = "Logan Tolbert",
                            Content = "A beginner's guide to building web APIs using ASP.NET Core.",
                            CreatedAt = new DateTime(2025, 5, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Tags = "ASP.NET Core,Web API",
                            Title = "Understanding ASP.NET Core",
                            UpdatedAt = new DateTime(2025, 5, 9, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            Author = "Logan Tolbert",
                            Content = "Learn how to use EF Core for data access in .NET applications.",
                            CreatedAt = new DateTime(2025, 5, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Tags = "EF Core,Database,ORM",
                            Title = "Working with Entity Framework Core",
                            UpdatedAt = new DateTime(2025, 5, 9, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            Author = "Logan Tolbert",
                            Content = "An introduction to containerization using Docker.",
                            CreatedAt = new DateTime(2025, 5, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Tags = "Docker,DevOps,Containers",
                            Title = "Getting Started with Docker",
                            UpdatedAt = new DateTime(2025, 5, 9, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            Author = "Logan Tolbert",
                            Content = "Overview of designing and building microservices applications.",
                            CreatedAt = new DateTime(2025, 5, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Tags = "Microservices,Architecture,Cloud",
                            Title = "Microservices Architecture Basics",
                            UpdatedAt = new DateTime(2025, 5, 9, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            Author = "Logan Tolbert",
                            Content = "How to create and deploy serverless APIs using AWS Lambda and API Gateway.",
                            CreatedAt = new DateTime(2025, 5, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Tags = "AWS,Lambda,Serverless,API",
                            Title = "Serverless API with AWS Lambda",
                            UpdatedAt = new DateTime(2025, 5, 9, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
